---
title: "Untitled"
output: html_document
---
```{r}
library(tidyverse)
library(data.table)
path <- "/media/ad/01D6B57CFBE4DB20/1.Linux/Data/household_power_consumption.txt"
dt <- fread(path)
dim(dt) # 2075259 9
head(dt)
tail(dt)
```

```{r}
data <- dt[Date == "1/2/2007" | Date =="2/2/2007"]
data
```


```{r}
library(hms)
library(lubridate)
#data$Date <- as.Date(as.character(data$Date), '%d-%m-%y')
data$Date <- lubridate::dmy(data$Date)
#data$Date <- as_date(data$Date)
data$Time <- as_hms(data$Time)
data <- data %>% mutate_if(is.character,as.numeric)
head(data)
```
```{r}
data$date_time <- paste(data$Date,data$Time)
data$date_time <- ymd_hms(data$date_time )
head(data)
```

Plot 1
```{r}
with(data,hist(Global_active_power,main="Global Active Power",xlab="Global Active Power (kilowatts)",
               col = "red"))
```


Plot 2
```{r}
with(data,plot(date_time,Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab=""))
```

Plot 3
```{r}
data
```


```{r}
plot(data$date_time,data$Sub_metering_1,
type="l",xlab="", ylab="Energy sub metering")
lines(data$date_time,data$Sub_metering_2, col="red")
lines(data$date_time,data$Sub_metering_3, col="blue")
legend("topright"
       , col=c("black","red","blue")
       , c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  ")
       ,lty=c(1,1), lwd=c(1,1))
```

Plot4
```{r}
par(mfrow =c(2,2))
with(data, {
  plot(date_time,Global_active_power,type="l",ylab="Global Active Power",xlab="")
  plot(date_time,Voltage,type="l",ylab="Voltage",xlab="")
  plot(data$date_time,data$Sub_metering_1,
  type="l",xlab="", ylab="Energy sub metering")
  lines(data$date_time,data$Sub_metering_2, col="red")
  lines(data$date_time,data$Sub_metering_3, col="blue")
  legend("topright"
       , col=c("black","red","blue")
       , c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  ")
       ,lty=c(1,1), bty="n", cex=.5)
  plot(date_time,Global_reactive_power,type="l",ylab="Global_ractive_power",xlab="")
})
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

